SELECT SUM("SCH_DISCWODIS_MULTOOS_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WODIS_MULTOOS_rate
, SUM("SCH_DISCWODIS_MULTOOS_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WODIS_MULTOOS_rate
, SUM("SCH_DISCWODIS_MULTOOS_WH_F" + "SCH_DISCWODIS_MULTOOS_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WODIS_MULTOOS_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WDIS_MULTOOS_IDEA_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WDIS_MULTOOS_IDEA_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_WH_F" + "SCH_DISCWDIS_MULTOOS_IDEA_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WDIS_MULTOOS_IDEA_rate
, SUM("SCH_DISCWODIS_SINGOOS_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WODIS_SINGOOS_rate
, SUM("SCH_DISCWODIS_SINGOOS_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WODIS_SINGOOS_rate
, SUM("SCH_DISCWODIS_SINGOOS_WH_F" + "SCH_DISCWODIS_SINGOOS_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WODIS_SINGOOS_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WDIS_SINGOOS_IDEA_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WDIS_SINGOOS_IDEA_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_WH_F" + "SCH_DISCWDIS_SINGOOS_IDEA_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WDIS_SINGOOS_IDEA_rate
, SUM("SCH_DISCWODIS_REF_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WODIS_REF_rate
, SUM("SCH_DISCWODIS_REF_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WODIS_REF_rate
, SUM("SCH_DISCWODIS_REF_WH_F" + "SCH_DISCWODIS_REF_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WODIS_REF_rate
, SUM("SCH_DISCWDIS_REF_IDEA_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWDIS_REF_IDEA_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWDIS_REF_IDEA_WH_F" + "SCH_DISCWDIS_REF_IDEA_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWODIS_ARR_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WODIS_ARR_rate
, SUM("SCH_DISCWODIS_ARR_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WODIS_ARR_rate
, SUM("SCH_DISCWODIS_ARR_WH_F" + "SCH_DISCWODIS_ARR_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WODIS_ARR_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WDIS_ARR_IDEA_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WDIS_ARR_IDEA_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_WH_F" + "SCH_DISCWDIS_ARR_IDEA_WH_M") / SUM((NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0))) as WH_both_genders_WDIS_ARR_IDEA_rate
from districts;
