SELECT ("bl_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as bl_m_wodis_multoos_risk_ratio_all_races
	, ("bl_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as bl_m_wodis_multoos_risk_ratio_white
	, ("bl_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as bl_f_wodis_multoos_risk_ratio_all_races
	, ("bl_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as bl_f_wodis_multoos_risk_ratio_white
	, ("bl_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as bl_both_genders_wodis_multoos_risk_ratio_all_races
	, ("bl_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as bl_both_genders_wodis_multoos_risk_ratio_white
	, ("wh_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as wh_m_wodis_multoos_risk_ratio_all_races
	, ("wh_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as wh_m_wodis_multoos_risk_ratio_white
	, ("wh_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as wh_f_wodis_multoos_risk_ratio_all_races
	, ("wh_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as wh_f_wodis_multoos_risk_ratio_white
	, ("wh_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as wh_both_genders_wodis_multoos_risk_ratio_all_races
	, ("wh_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as wh_both_genders_wodis_multoos_risk_ratio_white
	, ("am_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as am_m_wodis_multoos_risk_ratio_all_races
	, ("am_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as am_m_wodis_multoos_risk_ratio_white
	, ("am_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as am_f_wodis_multoos_risk_ratio_all_races
	, ("am_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as am_f_wodis_multoos_risk_ratio_white
	, ("am_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as am_both_genders_wodis_multoos_risk_ratio_all_races
	, ("am_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as am_both_genders_wodis_multoos_risk_ratio_white
	, ("as_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as as_m_wodis_multoos_risk_ratio_all_races
	, ("as_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as as_m_wodis_multoos_risk_ratio_white
	, ("as_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as as_f_wodis_multoos_risk_ratio_all_races
	, ("as_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as as_f_wodis_multoos_risk_ratio_white
	, ("as_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as as_both_genders_wodis_multoos_risk_ratio_all_races
	, ("as_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as as_both_genders_wodis_multoos_risk_ratio_white
	, ("hi_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as hi_m_wodis_multoos_risk_ratio_all_races
	, ("hi_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as hi_m_wodis_multoos_risk_ratio_white
	, ("hi_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as hi_f_wodis_multoos_risk_ratio_all_races
	, ("hi_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as hi_f_wodis_multoos_risk_ratio_white
	, ("hi_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as hi_both_genders_wodis_multoos_risk_ratio_all_races
	, ("hi_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as hi_both_genders_wodis_multoos_risk_ratio_white
	, ("hp_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as hp_m_wodis_multoos_risk_ratio_all_races
	, ("hp_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as hp_m_wodis_multoos_risk_ratio_white
	, ("hp_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as hp_f_wodis_multoos_risk_ratio_all_races
	, ("hp_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as hp_f_wodis_multoos_risk_ratio_white
	, ("hp_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as hp_both_genders_wodis_multoos_risk_ratio_all_races
	, ("hp_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as hp_both_genders_wodis_multoos_risk_ratio_white
	, ("tr_m_wodis_multoos_rate" / "ntl_all_races_m_wodis_multoos_rate") as tr_m_wodis_multoos_risk_ratio_all_races
	, ("tr_m_wodis_multoos_rate" / "ntl_wh_m_wodis_multoos_rate") as tr_m_wodis_multoos_risk_ratio_white
	, ("tr_f_wodis_multoos_rate" / "ntl_all_races_f_wodis_multoos_rate") as tr_f_wodis_multoos_risk_ratio_all_races
	, ("tr_f_wodis_multoos_rate" / "ntl_wh_f_wodis_multoos_rate") as tr_f_wodis_multoos_risk_ratio_white
	, ("tr_both_genders_wodis_multoos_rate" / "ntl_all_races_both_genders_wodis_multoos_rate") as tr_both_genders_wodis_multoos_risk_ratio_all_races
	, ("tr_both_genders_wodis_multoos_rate" / "ntl_wh_both_genders_wodis_multoos_rate") as tr_both_genders_wodis_multoos_risk_ratio_white
	, ("bl_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as bl_m_wdis_multoos_idea_risk_ratio_all_races
	, ("bl_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as bl_m_wdis_multoos_idea_risk_ratio_white
	, ("bl_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as bl_f_wdis_multoos_idea_risk_ratio_all_races
	, ("bl_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as bl_f_wdis_multoos_idea_risk_ratio_white
	, ("bl_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as bl_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("bl_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as bl_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("wh_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as wh_m_wdis_multoos_idea_risk_ratio_all_races
	, ("wh_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as wh_m_wdis_multoos_idea_risk_ratio_white
	, ("wh_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as wh_f_wdis_multoos_idea_risk_ratio_all_races
	, ("wh_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as wh_f_wdis_multoos_idea_risk_ratio_white
	, ("wh_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as wh_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("wh_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as wh_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("am_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as am_m_wdis_multoos_idea_risk_ratio_all_races
	, ("am_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as am_m_wdis_multoos_idea_risk_ratio_white
	, ("am_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as am_f_wdis_multoos_idea_risk_ratio_all_races
	, ("am_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as am_f_wdis_multoos_idea_risk_ratio_white
	, ("am_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as am_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("am_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as am_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("as_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as as_m_wdis_multoos_idea_risk_ratio_all_races
	, ("as_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as as_m_wdis_multoos_idea_risk_ratio_white
	, ("as_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as as_f_wdis_multoos_idea_risk_ratio_all_races
	, ("as_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as as_f_wdis_multoos_idea_risk_ratio_white
	, ("as_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as as_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("as_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as as_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("hi_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as hi_m_wdis_multoos_idea_risk_ratio_all_races
	, ("hi_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as hi_m_wdis_multoos_idea_risk_ratio_white
	, ("hi_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as hi_f_wdis_multoos_idea_risk_ratio_all_races
	, ("hi_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as hi_f_wdis_multoos_idea_risk_ratio_white
	, ("hi_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as hi_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("hi_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as hi_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("hp_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as hp_m_wdis_multoos_idea_risk_ratio_all_races
	, ("hp_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as hp_m_wdis_multoos_idea_risk_ratio_white
	, ("hp_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as hp_f_wdis_multoos_idea_risk_ratio_all_races
	, ("hp_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as hp_f_wdis_multoos_idea_risk_ratio_white
	, ("hp_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as hp_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("hp_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as hp_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("tr_m_wdis_multoos_idea_rate" / "ntl_all_races_m_wdis_multoos_idea_rate") as tr_m_wdis_multoos_idea_risk_ratio_all_races
	, ("tr_m_wdis_multoos_idea_rate" / "ntl_wh_m_wdis_multoos_idea_rate") as tr_m_wdis_multoos_idea_risk_ratio_white
	, ("tr_f_wdis_multoos_idea_rate" / "ntl_all_races_f_wdis_multoos_idea_rate") as tr_f_wdis_multoos_idea_risk_ratio_all_races
	, ("tr_f_wdis_multoos_idea_rate" / "ntl_wh_f_wdis_multoos_idea_rate") as tr_f_wdis_multoos_idea_risk_ratio_white
	, ("tr_both_genders_wdis_multoos_idea_rate" / "ntl_all_races_both_genders_wdis_multoos_idea_rate") as tr_both_genders_wdis_multoos_idea_risk_ratio_all_races
	, ("tr_both_genders_wdis_multoos_idea_rate" / "ntl_wh_both_genders_wdis_multoos_idea_rate") as tr_both_genders_wdis_multoos_idea_risk_ratio_white
	, ("bl_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as bl_m_wodis_singoos_risk_ratio_all_races
	, ("bl_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as bl_m_wodis_singoos_risk_ratio_white
	, ("bl_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as bl_f_wodis_singoos_risk_ratio_all_races
	, ("bl_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as bl_f_wodis_singoos_risk_ratio_white
	, ("bl_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as bl_both_genders_wodis_singoos_risk_ratio_all_races
	, ("bl_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as bl_both_genders_wodis_singoos_risk_ratio_white
	, ("wh_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as wh_m_wodis_singoos_risk_ratio_all_races
	, ("wh_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as wh_m_wodis_singoos_risk_ratio_white
	, ("wh_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as wh_f_wodis_singoos_risk_ratio_all_races
	, ("wh_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as wh_f_wodis_singoos_risk_ratio_white
	, ("wh_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as wh_both_genders_wodis_singoos_risk_ratio_all_races
	, ("wh_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as wh_both_genders_wodis_singoos_risk_ratio_white
	, ("am_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as am_m_wodis_singoos_risk_ratio_all_races
	, ("am_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as am_m_wodis_singoos_risk_ratio_white
	, ("am_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as am_f_wodis_singoos_risk_ratio_all_races
	, ("am_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as am_f_wodis_singoos_risk_ratio_white
	, ("am_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as am_both_genders_wodis_singoos_risk_ratio_all_races
	, ("am_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as am_both_genders_wodis_singoos_risk_ratio_white
	, ("as_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as as_m_wodis_singoos_risk_ratio_all_races
	, ("as_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as as_m_wodis_singoos_risk_ratio_white
	, ("as_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as as_f_wodis_singoos_risk_ratio_all_races
	, ("as_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as as_f_wodis_singoos_risk_ratio_white
	, ("as_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as as_both_genders_wodis_singoos_risk_ratio_all_races
	, ("as_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as as_both_genders_wodis_singoos_risk_ratio_white
	, ("hi_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as hi_m_wodis_singoos_risk_ratio_all_races
	, ("hi_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as hi_m_wodis_singoos_risk_ratio_white
	, ("hi_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as hi_f_wodis_singoos_risk_ratio_all_races
	, ("hi_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as hi_f_wodis_singoos_risk_ratio_white
	, ("hi_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as hi_both_genders_wodis_singoos_risk_ratio_all_races
	, ("hi_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as hi_both_genders_wodis_singoos_risk_ratio_white
	, ("hp_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as hp_m_wodis_singoos_risk_ratio_all_races
	, ("hp_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as hp_m_wodis_singoos_risk_ratio_white
	, ("hp_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as hp_f_wodis_singoos_risk_ratio_all_races
	, ("hp_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as hp_f_wodis_singoos_risk_ratio_white
	, ("hp_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as hp_both_genders_wodis_singoos_risk_ratio_all_races
	, ("hp_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as hp_both_genders_wodis_singoos_risk_ratio_white
	, ("tr_m_wodis_singoos_rate" / "ntl_all_races_m_wodis_singoos_rate") as tr_m_wodis_singoos_risk_ratio_all_races
	, ("tr_m_wodis_singoos_rate" / "ntl_wh_m_wodis_singoos_rate") as tr_m_wodis_singoos_risk_ratio_white
	, ("tr_f_wodis_singoos_rate" / "ntl_all_races_f_wodis_singoos_rate") as tr_f_wodis_singoos_risk_ratio_all_races
	, ("tr_f_wodis_singoos_rate" / "ntl_wh_f_wodis_singoos_rate") as tr_f_wodis_singoos_risk_ratio_white
	, ("tr_both_genders_wodis_singoos_rate" / "ntl_all_races_both_genders_wodis_singoos_rate") as tr_both_genders_wodis_singoos_risk_ratio_all_races
	, ("tr_both_genders_wodis_singoos_rate" / "ntl_wh_both_genders_wodis_singoos_rate") as tr_both_genders_wodis_singoos_risk_ratio_white
	, ("bl_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as bl_m_wdis_singoos_idea_risk_ratio_all_races
	, ("bl_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as bl_m_wdis_singoos_idea_risk_ratio_white
	, ("bl_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as bl_f_wdis_singoos_idea_risk_ratio_all_races
	, ("bl_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as bl_f_wdis_singoos_idea_risk_ratio_white
	, ("bl_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as bl_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("bl_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as bl_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("wh_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as wh_m_wdis_singoos_idea_risk_ratio_all_races
	, ("wh_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as wh_m_wdis_singoos_idea_risk_ratio_white
	, ("wh_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as wh_f_wdis_singoos_idea_risk_ratio_all_races
	, ("wh_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as wh_f_wdis_singoos_idea_risk_ratio_white
	, ("wh_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as wh_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("wh_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as wh_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("am_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as am_m_wdis_singoos_idea_risk_ratio_all_races
	, ("am_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as am_m_wdis_singoos_idea_risk_ratio_white
	, ("am_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as am_f_wdis_singoos_idea_risk_ratio_all_races
	, ("am_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as am_f_wdis_singoos_idea_risk_ratio_white
	, ("am_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as am_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("am_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as am_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("as_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as as_m_wdis_singoos_idea_risk_ratio_all_races
	, ("as_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as as_m_wdis_singoos_idea_risk_ratio_white
	, ("as_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as as_f_wdis_singoos_idea_risk_ratio_all_races
	, ("as_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as as_f_wdis_singoos_idea_risk_ratio_white
	, ("as_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as as_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("as_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as as_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("hi_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as hi_m_wdis_singoos_idea_risk_ratio_all_races
	, ("hi_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as hi_m_wdis_singoos_idea_risk_ratio_white
	, ("hi_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as hi_f_wdis_singoos_idea_risk_ratio_all_races
	, ("hi_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as hi_f_wdis_singoos_idea_risk_ratio_white
	, ("hi_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as hi_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("hi_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as hi_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("hp_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as hp_m_wdis_singoos_idea_risk_ratio_all_races
	, ("hp_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as hp_m_wdis_singoos_idea_risk_ratio_white
	, ("hp_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as hp_f_wdis_singoos_idea_risk_ratio_all_races
	, ("hp_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as hp_f_wdis_singoos_idea_risk_ratio_white
	, ("hp_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as hp_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("hp_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as hp_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("tr_m_wdis_singoos_idea_rate" / "ntl_all_races_m_wdis_singoos_idea_rate") as tr_m_wdis_singoos_idea_risk_ratio_all_races
	, ("tr_m_wdis_singoos_idea_rate" / "ntl_wh_m_wdis_singoos_idea_rate") as tr_m_wdis_singoos_idea_risk_ratio_white
	, ("tr_f_wdis_singoos_idea_rate" / "ntl_all_races_f_wdis_singoos_idea_rate") as tr_f_wdis_singoos_idea_risk_ratio_all_races
	, ("tr_f_wdis_singoos_idea_rate" / "ntl_wh_f_wdis_singoos_idea_rate") as tr_f_wdis_singoos_idea_risk_ratio_white
	, ("tr_both_genders_wdis_singoos_idea_rate" / "ntl_all_races_both_genders_wdis_singoos_idea_rate") as tr_both_genders_wdis_singoos_idea_risk_ratio_all_races
	, ("tr_both_genders_wdis_singoos_idea_rate" / "ntl_wh_both_genders_wdis_singoos_idea_rate") as tr_both_genders_wdis_singoos_idea_risk_ratio_white
	, ("bl_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as bl_m_wodis_ref_risk_ratio_all_races
	, ("bl_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as bl_m_wodis_ref_risk_ratio_white
	, ("bl_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as bl_f_wodis_ref_risk_ratio_all_races
	, ("bl_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as bl_f_wodis_ref_risk_ratio_white
	, ("bl_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as bl_both_genders_wodis_ref_risk_ratio_all_races
	, ("bl_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as bl_both_genders_wodis_ref_risk_ratio_white
	, ("wh_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as wh_m_wodis_ref_risk_ratio_all_races
	, ("wh_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as wh_m_wodis_ref_risk_ratio_white
	, ("wh_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as wh_f_wodis_ref_risk_ratio_all_races
	, ("wh_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as wh_f_wodis_ref_risk_ratio_white
	, ("wh_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as wh_both_genders_wodis_ref_risk_ratio_all_races
	, ("wh_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as wh_both_genders_wodis_ref_risk_ratio_white
	, ("am_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as am_m_wodis_ref_risk_ratio_all_races
	, ("am_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as am_m_wodis_ref_risk_ratio_white
	, ("am_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as am_f_wodis_ref_risk_ratio_all_races
	, ("am_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as am_f_wodis_ref_risk_ratio_white
	, ("am_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as am_both_genders_wodis_ref_risk_ratio_all_races
	, ("am_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as am_both_genders_wodis_ref_risk_ratio_white
	, ("as_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as as_m_wodis_ref_risk_ratio_all_races
	, ("as_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as as_m_wodis_ref_risk_ratio_white
	, ("as_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as as_f_wodis_ref_risk_ratio_all_races
	, ("as_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as as_f_wodis_ref_risk_ratio_white
	, ("as_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as as_both_genders_wodis_ref_risk_ratio_all_races
	, ("as_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as as_both_genders_wodis_ref_risk_ratio_white
	, ("hi_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as hi_m_wodis_ref_risk_ratio_all_races
	, ("hi_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as hi_m_wodis_ref_risk_ratio_white
	, ("hi_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as hi_f_wodis_ref_risk_ratio_all_races
	, ("hi_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as hi_f_wodis_ref_risk_ratio_white
	, ("hi_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as hi_both_genders_wodis_ref_risk_ratio_all_races
	, ("hi_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as hi_both_genders_wodis_ref_risk_ratio_white
	, ("hp_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as hp_m_wodis_ref_risk_ratio_all_races
	, ("hp_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as hp_m_wodis_ref_risk_ratio_white
	, ("hp_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as hp_f_wodis_ref_risk_ratio_all_races
	, ("hp_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as hp_f_wodis_ref_risk_ratio_white
	, ("hp_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as hp_both_genders_wodis_ref_risk_ratio_all_races
	, ("hp_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as hp_both_genders_wodis_ref_risk_ratio_white
	, ("tr_m_wodis_ref_rate" / "ntl_all_races_m_wodis_ref_rate") as tr_m_wodis_ref_risk_ratio_all_races
	, ("tr_m_wodis_ref_rate" / "ntl_wh_m_wodis_ref_rate") as tr_m_wodis_ref_risk_ratio_white
	, ("tr_f_wodis_ref_rate" / "ntl_all_races_f_wodis_ref_rate") as tr_f_wodis_ref_risk_ratio_all_races
	, ("tr_f_wodis_ref_rate" / "ntl_wh_f_wodis_ref_rate") as tr_f_wodis_ref_risk_ratio_white
	, ("tr_both_genders_wodis_ref_rate" / "ntl_all_races_both_genders_wodis_ref_rate") as tr_both_genders_wodis_ref_risk_ratio_all_races
	, ("tr_both_genders_wodis_ref_rate" / "ntl_wh_both_genders_wodis_ref_rate") as tr_both_genders_wodis_ref_risk_ratio_white
	, ("bl_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as bl_m_wdis_ref_idea_risk_ratio_all_races
	, ("bl_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as bl_m_wdis_ref_idea_risk_ratio_white
	, ("bl_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as bl_f_wdis_ref_idea_risk_ratio_all_races
	, ("bl_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as bl_f_wdis_ref_idea_risk_ratio_white
	, ("bl_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as bl_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("bl_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as bl_both_genders_wdis_ref_idea_risk_ratio_white
	, ("wh_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as wh_m_wdis_ref_idea_risk_ratio_all_races
	, ("wh_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as wh_m_wdis_ref_idea_risk_ratio_white
	, ("wh_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as wh_f_wdis_ref_idea_risk_ratio_all_races
	, ("wh_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as wh_f_wdis_ref_idea_risk_ratio_white
	, ("wh_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as wh_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("wh_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as wh_both_genders_wdis_ref_idea_risk_ratio_white
	, ("am_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as am_m_wdis_ref_idea_risk_ratio_all_races
	, ("am_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as am_m_wdis_ref_idea_risk_ratio_white
	, ("am_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as am_f_wdis_ref_idea_risk_ratio_all_races
	, ("am_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as am_f_wdis_ref_idea_risk_ratio_white
	, ("am_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as am_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("am_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as am_both_genders_wdis_ref_idea_risk_ratio_white
	, ("as_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as as_m_wdis_ref_idea_risk_ratio_all_races
	, ("as_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as as_m_wdis_ref_idea_risk_ratio_white
	, ("as_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as as_f_wdis_ref_idea_risk_ratio_all_races
	, ("as_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as as_f_wdis_ref_idea_risk_ratio_white
	, ("as_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as as_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("as_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as as_both_genders_wdis_ref_idea_risk_ratio_white
	, ("hi_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as hi_m_wdis_ref_idea_risk_ratio_all_races
	, ("hi_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as hi_m_wdis_ref_idea_risk_ratio_white
	, ("hi_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as hi_f_wdis_ref_idea_risk_ratio_all_races
	, ("hi_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as hi_f_wdis_ref_idea_risk_ratio_white
	, ("hi_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as hi_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("hi_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as hi_both_genders_wdis_ref_idea_risk_ratio_white
	, ("hp_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as hp_m_wdis_ref_idea_risk_ratio_all_races
	, ("hp_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as hp_m_wdis_ref_idea_risk_ratio_white
	, ("hp_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as hp_f_wdis_ref_idea_risk_ratio_all_races
	, ("hp_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as hp_f_wdis_ref_idea_risk_ratio_white
	, ("hp_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as hp_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("hp_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as hp_both_genders_wdis_ref_idea_risk_ratio_white
	, ("tr_m_wdis_ref_idea_rate" / "ntl_all_races_m_wdis_ref_idea_rate") as tr_m_wdis_ref_idea_risk_ratio_all_races
	, ("tr_m_wdis_ref_idea_rate" / "ntl_wh_m_wdis_ref_idea_rate") as tr_m_wdis_ref_idea_risk_ratio_white
	, ("tr_f_wdis_ref_idea_rate" / "ntl_all_races_f_wdis_ref_idea_rate") as tr_f_wdis_ref_idea_risk_ratio_all_races
	, ("tr_f_wdis_ref_idea_rate" / "ntl_wh_f_wdis_ref_idea_rate") as tr_f_wdis_ref_idea_risk_ratio_white
	, ("tr_both_genders_wdis_ref_idea_rate" / "ntl_all_races_both_genders_wdis_ref_idea_rate") as tr_both_genders_wdis_ref_idea_risk_ratio_all_races
	, ("tr_both_genders_wdis_ref_idea_rate" / "ntl_wh_both_genders_wdis_ref_idea_rate") as tr_both_genders_wdis_ref_idea_risk_ratio_white
	, ("bl_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as bl_m_wodis_arr_risk_ratio_all_races
	, ("bl_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as bl_m_wodis_arr_risk_ratio_white
	, ("bl_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as bl_f_wodis_arr_risk_ratio_all_races
	, ("bl_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as bl_f_wodis_arr_risk_ratio_white
	, ("bl_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as bl_both_genders_wodis_arr_risk_ratio_all_races
	, ("bl_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as bl_both_genders_wodis_arr_risk_ratio_white
	, ("wh_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as wh_m_wodis_arr_risk_ratio_all_races
	, ("wh_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as wh_m_wodis_arr_risk_ratio_white
	, ("wh_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as wh_f_wodis_arr_risk_ratio_all_races
	, ("wh_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as wh_f_wodis_arr_risk_ratio_white
	, ("wh_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as wh_both_genders_wodis_arr_risk_ratio_all_races
	, ("wh_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as wh_both_genders_wodis_arr_risk_ratio_white
	, ("am_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as am_m_wodis_arr_risk_ratio_all_races
	, ("am_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as am_m_wodis_arr_risk_ratio_white
	, ("am_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as am_f_wodis_arr_risk_ratio_all_races
	, ("am_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as am_f_wodis_arr_risk_ratio_white
	, ("am_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as am_both_genders_wodis_arr_risk_ratio_all_races
	, ("am_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as am_both_genders_wodis_arr_risk_ratio_white
	, ("as_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as as_m_wodis_arr_risk_ratio_all_races
	, ("as_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as as_m_wodis_arr_risk_ratio_white
	, ("as_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as as_f_wodis_arr_risk_ratio_all_races
	, ("as_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as as_f_wodis_arr_risk_ratio_white
	, ("as_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as as_both_genders_wodis_arr_risk_ratio_all_races
	, ("as_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as as_both_genders_wodis_arr_risk_ratio_white
	, ("hi_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as hi_m_wodis_arr_risk_ratio_all_races
	, ("hi_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as hi_m_wodis_arr_risk_ratio_white
	, ("hi_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as hi_f_wodis_arr_risk_ratio_all_races
	, ("hi_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as hi_f_wodis_arr_risk_ratio_white
	, ("hi_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as hi_both_genders_wodis_arr_risk_ratio_all_races
	, ("hi_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as hi_both_genders_wodis_arr_risk_ratio_white
	, ("hp_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as hp_m_wodis_arr_risk_ratio_all_races
	, ("hp_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as hp_m_wodis_arr_risk_ratio_white
	, ("hp_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as hp_f_wodis_arr_risk_ratio_all_races
	, ("hp_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as hp_f_wodis_arr_risk_ratio_white
	, ("hp_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as hp_both_genders_wodis_arr_risk_ratio_all_races
	, ("hp_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as hp_both_genders_wodis_arr_risk_ratio_white
	, ("tr_m_wodis_arr_rate" / "ntl_all_races_m_wodis_arr_rate") as tr_m_wodis_arr_risk_ratio_all_races
	, ("tr_m_wodis_arr_rate" / "ntl_wh_m_wodis_arr_rate") as tr_m_wodis_arr_risk_ratio_white
	, ("tr_f_wodis_arr_rate" / "ntl_all_races_f_wodis_arr_rate") as tr_f_wodis_arr_risk_ratio_all_races
	, ("tr_f_wodis_arr_rate" / "ntl_wh_f_wodis_arr_rate") as tr_f_wodis_arr_risk_ratio_white
	, ("tr_both_genders_wodis_arr_rate" / "ntl_all_races_both_genders_wodis_arr_rate") as tr_both_genders_wodis_arr_risk_ratio_all_races
	, ("tr_both_genders_wodis_arr_rate" / "ntl_wh_both_genders_wodis_arr_rate") as tr_both_genders_wodis_arr_risk_ratio_white
	, ("bl_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as bl_m_wdis_arr_idea_risk_ratio_all_races
	, ("bl_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as bl_m_wdis_arr_idea_risk_ratio_white
	, ("bl_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as bl_f_wdis_arr_idea_risk_ratio_all_races
	, ("bl_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as bl_f_wdis_arr_idea_risk_ratio_white
	, ("bl_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as bl_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("bl_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as bl_both_genders_wdis_arr_idea_risk_ratio_white
	, ("wh_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as wh_m_wdis_arr_idea_risk_ratio_all_races
	, ("wh_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as wh_m_wdis_arr_idea_risk_ratio_white
	, ("wh_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as wh_f_wdis_arr_idea_risk_ratio_all_races
	, ("wh_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as wh_f_wdis_arr_idea_risk_ratio_white
	, ("wh_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as wh_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("wh_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as wh_both_genders_wdis_arr_idea_risk_ratio_white
	, ("am_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as am_m_wdis_arr_idea_risk_ratio_all_races
	, ("am_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as am_m_wdis_arr_idea_risk_ratio_white
	, ("am_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as am_f_wdis_arr_idea_risk_ratio_all_races
	, ("am_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as am_f_wdis_arr_idea_risk_ratio_white
	, ("am_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as am_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("am_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as am_both_genders_wdis_arr_idea_risk_ratio_white
	, ("as_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as as_m_wdis_arr_idea_risk_ratio_all_races
	, ("as_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as as_m_wdis_arr_idea_risk_ratio_white
	, ("as_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as as_f_wdis_arr_idea_risk_ratio_all_races
	, ("as_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as as_f_wdis_arr_idea_risk_ratio_white
	, ("as_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as as_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("as_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as as_both_genders_wdis_arr_idea_risk_ratio_white
	, ("hi_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as hi_m_wdis_arr_idea_risk_ratio_all_races
	, ("hi_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as hi_m_wdis_arr_idea_risk_ratio_white
	, ("hi_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as hi_f_wdis_arr_idea_risk_ratio_all_races
	, ("hi_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as hi_f_wdis_arr_idea_risk_ratio_white
	, ("hi_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as hi_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("hi_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as hi_both_genders_wdis_arr_idea_risk_ratio_white
	, ("hp_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as hp_m_wdis_arr_idea_risk_ratio_all_races
	, ("hp_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as hp_m_wdis_arr_idea_risk_ratio_white
	, ("hp_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as hp_f_wdis_arr_idea_risk_ratio_all_races
	, ("hp_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as hp_f_wdis_arr_idea_risk_ratio_white
	, ("hp_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as hp_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("hp_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as hp_both_genders_wdis_arr_idea_risk_ratio_white
	, ("tr_m_wdis_arr_idea_rate" / "ntl_all_races_m_wdis_arr_idea_rate") as tr_m_wdis_arr_idea_risk_ratio_all_races
	, ("tr_m_wdis_arr_idea_rate" / "ntl_wh_m_wdis_arr_idea_rate") as tr_m_wdis_arr_idea_risk_ratio_white
	, ("tr_f_wdis_arr_idea_rate" / "ntl_all_races_f_wdis_arr_idea_rate") as tr_f_wdis_arr_idea_risk_ratio_all_races
	, ("tr_f_wdis_arr_idea_rate" / "ntl_wh_f_wdis_arr_idea_rate") as tr_f_wdis_arr_idea_risk_ratio_white
	, ("tr_both_genders_wdis_arr_idea_rate" / "ntl_all_races_both_genders_wdis_arr_idea_rate") as tr_both_genders_wdis_arr_idea_risk_ratio_all_races
	, ("tr_both_genders_wdis_arr_idea_rate" / "ntl_wh_both_genders_wdis_arr_idea_rate") as tr_both_genders_wdis_arr_idea_risk_ratio_white
	FROM
(SELECT * FROM district_rates CROSS JOIN national_rates) full_table;


