DROP TABLE if exists national_rates;

CREATE TABLE national_rates as (
Select 1
, SUM("SCH_DISCWODIS_MULTOOS_BL_M" + "SCH_DISCWODIS_SINGOOS_BL_M") / SUM(NULLIF("SCH_ENR_BL_M", 0)) as BL_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_BL_F" + "SCH_DISCWODIS_SINGOOS_BL_F") / SUM(NULLIF("SCH_ENR_BL_F", 0)) as BL_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_BL_M" + "SCH_DISCWODIS_SINGOOS_BL_F" + "SCH_DISCWODIS_MULTOOS_BL_F" + "SCH_DISCWODIS_MULTOOS_BL_M") / SUM(NULLIF("SCH_ENR_BL_F", 0) + NULLIF("SCH_ENR_BL_M", 0)) as ntl_BL_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_WH_M" + "SCH_DISCWODIS_SINGOOS_WH_M") / SUM(NULLIF("SCH_ENR_WH_M", 0)) as WH_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_WH_F" + "SCH_DISCWODIS_SINGOOS_WH_F") / SUM(NULLIF("SCH_ENR_WH_F", 0)) as WH_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_WH_M" + "SCH_DISCWODIS_SINGOOS_WH_F" + "SCH_DISCWODIS_MULTOOS_WH_F" + "SCH_DISCWODIS_MULTOOS_WH_M") / SUM(NULLIF("SCH_ENR_WH_F", 0) + NULLIF("SCH_ENR_WH_M", 0)) as ntl_WH_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_AM_M" + "SCH_DISCWODIS_SINGOOS_AM_M") / SUM(NULLIF("SCH_ENR_AM_M", 0)) as AM_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_AM_F" + "SCH_DISCWODIS_SINGOOS_AM_F") / SUM(NULLIF("SCH_ENR_AM_F", 0)) as AM_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_AM_M" + "SCH_DISCWODIS_SINGOOS_AM_F" + "SCH_DISCWODIS_MULTOOS_AM_F" + "SCH_DISCWODIS_MULTOOS_AM_M") / SUM(NULLIF("SCH_ENR_AM_F", 0) + NULLIF("SCH_ENR_AM_M", 0)) as ntl_AM_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_AS_M" + "SCH_DISCWODIS_SINGOOS_AS_M") / SUM(NULLIF("SCH_ENR_AS_M", 0)) as AS_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_AS_F" + "SCH_DISCWODIS_SINGOOS_AS_F") / SUM(NULLIF("SCH_ENR_AS_F", 0)) as AS_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_AS_M" + "SCH_DISCWODIS_SINGOOS_AS_F" + "SCH_DISCWODIS_MULTOOS_AS_F" + "SCH_DISCWODIS_MULTOOS_AS_M") / SUM(NULLIF("SCH_ENR_AS_F", 0) + NULLIF("SCH_ENR_AS_M", 0)) as ntl_AS_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_HI_M" + "SCH_DISCWODIS_SINGOOS_HI_M") / SUM(NULLIF("SCH_ENR_HI_M", 0)) as HI_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_HI_F" + "SCH_DISCWODIS_SINGOOS_HI_F") / SUM(NULLIF("SCH_ENR_HI_F", 0)) as HI_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_HI_M" + "SCH_DISCWODIS_SINGOOS_HI_F" + "SCH_DISCWODIS_MULTOOS_HI_F" + "SCH_DISCWODIS_MULTOOS_HI_M") / SUM(NULLIF("SCH_ENR_HI_F", 0) + NULLIF("SCH_ENR_HI_M", 0)) as ntl_HI_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_HP_M" + "SCH_DISCWODIS_SINGOOS_HP_M") / SUM(NULLIF("SCH_ENR_HP_M", 0)) as HP_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_HP_F" + "SCH_DISCWODIS_SINGOOS_HP_F") / SUM(NULLIF("SCH_ENR_HP_F", 0)) as HP_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_HP_M" + "SCH_DISCWODIS_SINGOOS_HP_F" + "SCH_DISCWODIS_MULTOOS_HP_F" + "SCH_DISCWODIS_MULTOOS_HP_M") / SUM(NULLIF("SCH_ENR_HP_F", 0) + NULLIF("SCH_ENR_HP_M", 0)) as ntl_HP_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_TR_M" + "SCH_DISCWODIS_SINGOOS_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as TR_M_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_MULTOOS_TR_F" + "SCH_DISCWODIS_SINGOOS_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as TR_F_WODIS_suspension_rate
, SUM("SCH_DISCWODIS_SINGOOS_TR_M" + "SCH_DISCWODIS_SINGOOS_TR_F" + "SCH_DISCWODIS_MULTOOS_TR_F" + "SCH_DISCWODIS_MULTOOS_TR_M") / SUM(NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_both_genders_WODIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_BL_M" + "SCH_DISCWDIS_SINGOOS_IDEA_BL_M") / SUM(NULLIF("SCH_IDEAENR_BL_M", 0)) as BL_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_BL_F" + "SCH_DISCWDIS_SINGOOS_IDEA_BL_F") / SUM(NULLIF("SCH_IDEAENR_BL_F", 0)) as BL_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_BL_M" + "SCH_DISCWDIS_SINGOOS_IDEA_BL_F" + "SCH_DISCWDIS_MULTOOS_IDEA_BL_F" + "SCH_DISCWDIS_MULTOOS_IDEA_BL_M") / SUM(NULLIF("SCH_IDEAENR_BL_F", 0) + NULLIF("SCH_IDEAENR_BL_M", 0)) as ntl_BL_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_WH_M" + "SCH_DISCWDIS_SINGOOS_IDEA_WH_M") / SUM(NULLIF("SCH_IDEAENR_WH_M", 0)) as WH_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_WH_F" + "SCH_DISCWDIS_SINGOOS_IDEA_WH_F") / SUM(NULLIF("SCH_IDEAENR_WH_F", 0)) as WH_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_WH_M" + "SCH_DISCWDIS_SINGOOS_IDEA_WH_F" + "SCH_DISCWDIS_MULTOOS_IDEA_WH_F" + "SCH_DISCWDIS_MULTOOS_IDEA_WH_M") / SUM(NULLIF("SCH_IDEAENR_WH_F", 0) + NULLIF("SCH_IDEAENR_WH_M", 0)) as ntl_WH_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_AM_M" + "SCH_DISCWDIS_SINGOOS_IDEA_AM_M") / SUM(NULLIF("SCH_IDEAENR_AM_M", 0)) as AM_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_AM_F" + "SCH_DISCWDIS_SINGOOS_IDEA_AM_F") / SUM(NULLIF("SCH_IDEAENR_AM_F", 0)) as AM_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_AM_M" + "SCH_DISCWDIS_SINGOOS_IDEA_AM_F" + "SCH_DISCWDIS_MULTOOS_IDEA_AM_F" + "SCH_DISCWDIS_MULTOOS_IDEA_AM_M") / SUM(NULLIF("SCH_IDEAENR_AM_F", 0) + NULLIF("SCH_IDEAENR_AM_M", 0)) as ntl_AM_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_AS_M" + "SCH_DISCWDIS_SINGOOS_IDEA_AS_M") / SUM(NULLIF("SCH_IDEAENR_AS_M", 0)) as AS_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_AS_F" + "SCH_DISCWDIS_SINGOOS_IDEA_AS_F") / SUM(NULLIF("SCH_IDEAENR_AS_F", 0)) as AS_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_AS_M" + "SCH_DISCWDIS_SINGOOS_IDEA_AS_F" + "SCH_DISCWDIS_MULTOOS_IDEA_AS_F" + "SCH_DISCWDIS_MULTOOS_IDEA_AS_M") / SUM(NULLIF("SCH_IDEAENR_AS_F", 0) + NULLIF("SCH_IDEAENR_AS_M", 0)) as ntl_AS_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_HI_M" + "SCH_DISCWDIS_SINGOOS_IDEA_HI_M") / SUM(NULLIF("SCH_IDEAENR_HI_M", 0)) as HI_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_HI_F" + "SCH_DISCWDIS_SINGOOS_IDEA_HI_F") / SUM(NULLIF("SCH_IDEAENR_HI_F", 0)) as HI_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_HI_M" + "SCH_DISCWDIS_SINGOOS_IDEA_HI_F" + "SCH_DISCWDIS_MULTOOS_IDEA_HI_F" + "SCH_DISCWDIS_MULTOOS_IDEA_HI_M") / SUM(NULLIF("SCH_IDEAENR_HI_F", 0) + NULLIF("SCH_IDEAENR_HI_M", 0)) as ntl_HI_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_HP_M" + "SCH_DISCWDIS_SINGOOS_IDEA_HP_M") / SUM(NULLIF("SCH_IDEAENR_HP_M", 0)) as HP_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_HP_F" + "SCH_DISCWDIS_SINGOOS_IDEA_HP_F") / SUM(NULLIF("SCH_IDEAENR_HP_F", 0)) as HP_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_HP_M" + "SCH_DISCWDIS_SINGOOS_IDEA_HP_F" + "SCH_DISCWDIS_MULTOOS_IDEA_HP_F" + "SCH_DISCWDIS_MULTOOS_IDEA_HP_M") / SUM(NULLIF("SCH_IDEAENR_HP_F", 0) + NULLIF("SCH_IDEAENR_HP_M", 0)) as ntl_HP_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_TR_M" + "SCH_DISCWDIS_SINGOOS_IDEA_TR_M") / SUM(NULLIF("SCH_IDEAENR_TR_M", 0)) as TR_M_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_MULTOOS_IDEA_TR_F" + "SCH_DISCWDIS_SINGOOS_IDEA_TR_F") / SUM(NULLIF("SCH_IDEAENR_TR_F", 0)) as TR_F_WDIS_suspension_rate
, SUM("SCH_DISCWDIS_SINGOOS_IDEA_TR_M" + "SCH_DISCWDIS_SINGOOS_IDEA_TR_F" + "SCH_DISCWDIS_MULTOOS_IDEA_TR_F" + "SCH_DISCWDIS_MULTOOS_IDEA_TR_M") / SUM(NULLIF("SCH_IDEAENR_TR_F", 0) + NULLIF("SCH_IDEAENR_TR_M", 0)) as ntl_TR_both_genders_WDIS_suspension_rate
, SUM("SCH_DISCWODIS_REF_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_WODIS_REF_rate
, SUM("SCH_DISCWODIS_REF_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_WODIS_REF_rate
, SUM("SCH_DISCWODIS_REF_TR_F" + "SCH_DISCWODIS_REF_TR_M") / SUM((NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0))) as ntl_TR_both_genders_WODIS_REF_rate
, SUM("SCH_DISCWDIS_REF_IDEA_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWDIS_REF_IDEA_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWDIS_REF_IDEA_TR_F" + "SCH_DISCWDIS_REF_IDEA_TR_M") / SUM((NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0))) as ntl_TR_both_genders_WDIS_REF_IDEA_rate
, SUM("SCH_DISCWODIS_ARR_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_WODIS_ARR_rate
, SUM("SCH_DISCWODIS_ARR_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_WODIS_ARR_rate
, SUM("SCH_DISCWODIS_ARR_TR_F" + "SCH_DISCWODIS_ARR_TR_M") / SUM((NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0))) as ntl_TR_both_genders_WODIS_ARR_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_WDIS_ARR_IDEA_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_WDIS_ARR_IDEA_rate
, SUM("SCH_DISCWDIS_ARR_IDEA_TR_F" + "SCH_DISCWDIS_ARR_IDEA_TR_M") / SUM((NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0))) as ntl_TR_both_genders_WDIS_ARR_IDEA_rate
, SUM("SCH_GTENR_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_GTENR_rate
, SUM("SCH_GTENR_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_GTENR_rate
, SUM("SCH_GTENR_TR_F" + "SCH_GTENR_TR_M") / SUM(NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_both_genders_GTENR_rate
, SUM("SCH_APENR_TR_M") / SUM(NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_M_APENR_rate
, SUM("SCH_APENR_TR_F") / SUM(NULLIF("SCH_ENR_TR_F", 0)) as ntl_TR_F_APENR_rate
, SUM("SCH_APENR_TR_F" + "SCH_APENR_TR_M") / SUM(NULLIF("SCH_ENR_TR_F", 0) + NULLIF("SCH_ENR_TR_M", 0)) as ntl_TR_both_genders_APENR_rate from districts;
FROM districts
);


